matrix:
  include:
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis-docker.sh
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis-docker.sh
    - os: osx
      language: generic
      env: PYTHON=python2 PYVER=2.7 URL=https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.6.pkg
      script: ./travis-osx.sh
    - os: osx
      language: generic
      env: PYTHON=python3 PYVER=3.4 URL=https://www.python.org/ftp/python/3.4.4/python-3.4.4-macosx10.6.pkg
      script: ./travis-osx.sh
    - os: osx
      language: generic
      env: PYTHON=python3 PYVER=3.5 URL=https://www.python.org/ftp/python/3.5.4/python-3.5.4-macosx10.6.pkg
      script: ./travis-osx.sh
    - os: osx
      language: generic
      env: PYTHON=python3 PYVER=3.6 URL=https://www.python.org/ftp/python/3.6.5/python-3.6.5-macosx10.6.pkg
      script: ./travis-osx.sh
