matrix:
  include:
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis.sh
    - sudo: required
      language: generic
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis.sh
    - os: osx
      language: generic
      script:
        - brew install python
        - python inspecter.py
        - python -m pip install nose
        - python setup.py build_ext -i
        - ls
        - otool -l libdemo.*
        - otool -l dtest.*
        - DYLD_LIBRARY_PATH="$PWD" python -m nose pipsnoop
